### ISSUE TITLE
Plugin Greyed Out After 1.0 Update (Krita 5.1.2)

### ISSUE THREAD

**Issue by cyanidearsenic** [Grum999/BuliBrushSwitch#17]
I recently noticed there was an update to Bulibrush, so I went to uninstall the old one, but the entry in the plugin manager is grayed out, so I can't uncheck it to disable it?
![image](https://github.com/Grum999/BuliBrushSwitch/assets/12106286/d4130fdd-f359-4a64-beed-5a95d06239a6)

So then I tried importing the newest version and letting it overwrite it when asked but even post-restarting, it's still greyed out and neither the toolbar button nor the keyboard shortcuts I tried putting in to get into the settings did anything

**Comment by Grum999** [comment]
Hi

When it's grayed in Krita's plugin list, it's because there's something wrong at startup.
There's 2 possibilities to check error at startup:
1) Move mouse over the grayed plugin in list, a tooltip will appear with some error messages (please provide it)
2) Starting krita from a terminal allows to get useful information about plugins failure at startup (in windows, need to use krita.com in cmd console to get messages) 

Also, are you using windows, linux, macos?

**Comment by cyanidearsenic** [comment]
Ooh, nice, I didn't know about the tooltips in the plugin manager.
![image](https://github.com/Grum999/BuliBrushSwitch/assets/12106286/181853ea-1720-48de-8068-b756f7b4378a)
I just grabbed a quick screenshot because I'm heading to an appointment soon, if you need it transcribed, I can do that in a few hours when I get back.
And I am using Windows.

**Comment by Grum999** [comment]
Looking at line 3077 of `bbswbrushes.py` file:
https://github.com/Grum999/BuliBrushSwitch/blob/597dd8a93ee3da08f76ae35dbe4c14ba80a18a8c/bulibrushswitch/bulibrushswitch/bbs/bbswbrushes.py#L3077C13-L3077C35

The `match` statement used is something new with Python 3.10 language: Krita 5.1.2 (from memory) use Python 3.8 
Maybe there's something else to review on my side because normally plugin won't try to activate with an explicit message if not installed on Krita 5.2 

If you test Krita 5.2, it should be ok (except if there's another problem we can't reach for now)

**Comment by Grum999** [comment]
Information about minimum required Krita version was not clearly provided, sorry.

I've just added an additional information to [release page](https://github.com/Grum999/BuliBrushSwitch/releases/tag/1.0.0)

> **Version 1.0.0 needs Krita > 5.2.0**
> *(not compatible with previous versions)*

**Comment by cyanidearsenic** [comment]
Sorry, for the delay getting back to you. (Work rudely getting in the way of me doing fun things!). The version doesn't seem to be specified exactly on the previous files each, 0.2.1b is the first one I saw that doesn't mention 5.2 specifically in the notes, is that one compatible with 5.1.5?

**Comment by Grum999** [comment]
No worries 🙂

Version 0.2.1b and previous needs Krita 5.0 or 5.1
Version 0.2.2b and next needs Krita 5.2

So as long as you stay on Krita 5.1.5 you have to use 0.2.1b 
If you have problem to install it, tell me (with error messages you got)

Not sure to create a 0.2.1c but at least we can try to understand what happen for you and try to find a solution
